fauna/faunadb-jvm

- faunadb-scala/src/main/scala/faunadb/query/Language.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
Shiny new syntax for Let and Lambda:
```scala
Let { val x = 1; val y = 2; Add(x, y) }
```
becomes
```json
{ "let": { "x": 1, "y": 2 }, "in": { "add": [{ "var": "x" }, { "var": "y" }] } }
```
and 
```scala
Lambda { (a, b, c) => [c, b, a] }
```
becomes
```json
{ "lambda": ["a", "b", "c"], "expr": [ { "var": "c" }, { "var": "b" }, { "var": "a" } ] }
```
> Macro lambda

- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/query/Language.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
removes the need for "quote", as expressions and values are differentiated at the type level, and we can convert values in a way to avoid the need for manual quoting.
> Expr type to separate expressions from values.

- faunadb-httpclient/src/main/java/com/faunadb/httpclient/Connection.java
The default was 60000, which is bigger than the server: 5000.
I've set to 4750 so we are sure that the client recycles the connection before the server closes it.
> Adjusting idle timeout for JVM drivers

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
It helps when creating short live connections with instances' tokens.
> Making JavaClient implements AutoCloseable interface

- faunadb-java/src/main/java/com/faunadb/client/types/Value.java
At the moment, I see no reason why custom values should be allowed
considering that they will not be covered by the value deserialization
mechanism.
Codec interface should be the most idiomatic way to create custom value
conversions.
> Making Value constructor private

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-common/src/main/java/com/faunadb/common/RefAwareHttpClient.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/test/FaunaDBTest.java
Major changes:
- Removing unnecessary exceptions from the `Connection.Builder` API
- Introducing API for short live connection sharing underneath resources
- Creating a builder for `FaunaClient` so we have a less verbose way to construct them
Minor:
- Renaming some variables and constants to conform to java conventions
- Do not create strings for debugging if debug level is disabled
> Improving driver initialisation

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java/src/main/java/com/faunadb/client/types/time/HighPrecisionTime.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
This implementation handles high precision time representations as neither Java 7 or JodaTime classes supports micro and nano second precision.
> Adding high precision time API

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/types/time/HighPrecisionTime.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
Reimplement `HighPrecisionTime` to use the same internal structure as it's implementation in Scala by #60.
> Refactor java time

- README.md
@ashfire908 I'm sorry. I've merged #78  without noticing that there was no link for maven artefacts.
> Fix maven badge

- LICENSE
- README.md
- build.sbt
Bumps copyright date and updates github links for the org change.
Part of https://github.com/fauna/sales-engineering/issues/525.
> Update driver info

- README.md
Since that module was extracted, the users can't really find the docs for the query language dsl.
> Adding java-dsl docs to the README file

- CHANGELOG.txt
- build.sbt
```
[warn] Class org.joda.convert.FromString not found - continuing with a stub.
[warn] Class org.joda.convert.ToString not found - continuing with a stub.
```
Those warning were getting out when using the scala driver as a dependency for your project.
> Add joda-convert in order to remove warnings

- README.md
While playing around with the [Fauna tutorial](https://fauna.com/tutorials/crud#getting-started) I noticed the tutorial code, which I was basing off of the samples in the JVM client readme file, was hanging both in SBT and running inside IntelliJ.  After a bit of digging I saw it's because we are not explicitly closing the FaunaClient, so we end up with some leftover netty threads sitting in `kevent0()`.  
Just to make the example more explicit and so nobody gets bit by the same thing, this patch simply adds the call to `close()`.  An alternative would be to wrap all the example code in a `sessionWith { ... }` function which is nice as it ties resource freeing with the tutorial logic falling out of scope, but this seemed like a less invasive change.
> README.md: examples: explicitly close client

- README.md
the published version 1.2.0 doesn't have the user defined classes encoder/decoders
> revert readme instructions to version 1.2.0

- faunadb-scala/src/main/scala/faunadb/query/package.scala
IDK why that has passed in my machine before submit the previous PR
> Fix comparison of different types on ngram function in scala driver

- CHANGELOG.txt
- README.md
- build.sbt
Nvidia reported that shading all guava code did not work on Jackson serializers so they come up with that package for us
> Release 1.2.6

- docs/scala.md
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-87](https://faunadb.atlassian.net/browse/DRV-87)
The `FaunaClient.query` method has been overloaded as follows:
```
def query(expr: Expr)(implicit ec: ExecutionContext): Future[Value] = query(expr, None)
def query(expr: Expr, timeout: FiniteDuration)(implicit ec: ExecutionContext): Future[Value] = ???
def query(expr: Expr, timeout: Option[FiniteDuration])(implicit ec: ExecutionContext): Future[Value] = ???
def query(exprs: Iterable[Expr])(implicit ec: ExecutionContext): Future[IndexedSeq[Value]] =
def query(exprs: Iterable[Expr], timeout: FiniteDuration)(implicit ec: ExecutionContext): Future[IndexedSeq[Value]] = ???
def query(exprs: Iterable[Expr], timeout: Option[FiniteDuration])(implicit ec: ExecutionContext): Future[IndexedSeq[Value]] = ???
```
> NOTE: For other alternative API …
> DRV-87: [scala] Add client-specified query timeout (overloading alternative)

- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
[DRV-117](https://faunadb.atlassian.net/browse/DRV-117)
This part of an old PR I had some time ago for the old private repo. Essentially, it refactors the implementation from an imperative to a more functional style.
I'll be updating this code as well as part of [DRV-87](https://faunadb.atlassian.net/browse/DRV-87), so I thought it was a good opportunity to get these changes in first!
> DRV-117: [scala] Unclutter query methods implementation in FaunaClient

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-206](https://faunadb.atlassian.net/browse/DRV-206)
The majority of the changes in this PR can be boiled down to replacing `await` for `futureValue`.  As a result, this will allows ScalaTest to give us a much better error response in case one of the tests fails.
> DRV-206: [scala] Use ScalaFutures in ClientSpec

- build.sbt
- project/Settings.scala
`publishSettings` was moved from the _root_ project to the subprojects as part of [DRV-170](https://faunadb.atlassian.net/browse/DRV-170). Nonetheless, it seems it needs to be set on the _root_ project in order to successfully run the `sbt sonatypeRelease` command when releasing.
> Move publish settings to root project

- build.sbt
- project/Settings.scala
Well, it looks like some settings from `buildSettings` and `publishSettings` are required both in the root and in the subprojects, so I've inclued all of them in all of the projects. Previous to [DRV-170](https://faunadb.atlassian.net/browse/DRV-170), this is how it was configured. 
Ideally, we should identify which settings actually belong to the root project and which ones to the subprojects.
> Include buildSettings and publishSettings in root and subprojects

- .circleci/config.yml
- build.sbt
- faunadb-common/src/main/java/com/faunadb/common/http/HttpClient.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientFixture.scala
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
- faunadb-scala/src/load/scala/faunadb/RandomGenerator.scala
- project/Configs.scala
- project/Settings.scala
- project/Tasks.scala
- project/Testing.scala
[DRV-264](https://faunadb.atlassian.net/browse/DRV-264)
- Content response limit set to `Integer.MAX_VALUE`
- Load-Test configuration added in sbt
- Load-Test configuration added for CircleCI
- A load-test test case added for covering a response of 10 MB of size is handled successfully
> DRV-264: Remove JVM driver’s 5mb network limit

- CHANGELOG.txt
- README.md
- project/Settings.scala
* Upgrade to Scala 2.12.12
* Upgrade to sbt 1.3.13
* Remove HTTP Response content size limit
* Define FaunaExceptions as case classes
* Remove unused .travis.yml file
* Remove unused AndroidManifest.xml file
> Release 3.0.1

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
While working for an extended period of time on the `ClientSpec` I often see the following error
```
14:33:30.794 [ForkJoinPool.commonPool-worker-5] INFO  com.faunadb.common.Connection - Request: POST http://localhost:8443: {"create_role":{"object":{"name":"a_role_cCOl02CD","privileges":{"object":{"resource":{"collections":null},"actions":{"object":{"read":true}}}}}}}. Failed: io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
java.util.concurrent.CompletionException: io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
| => fat …
```
> Reuse client Netty internals in ClientSpec

- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Ignore test cases evaluating `Contains` function so that we can move forward with the development while the function is introduced back in the `stable` Docker image.
> Ignore test cases evaluating Contains function

- .circleci/config.yml
The `stable` image will not be updated with latest changes for the foreseeable future. Most likely the image will be replaced by some other while we redesign our CI pipeline. Remove the job for now since new features cannot be tested against it  (e.g., streaming).
CircleCI is broken for some of the existing PRs due to cache permissions errors. Update cache key format to fix the current issue and prevent futures ones following best practices from:
* [Language Guide: Scala](https://circleci.com/docs/2.0/language-scala/)
* [Caching Dependencies](https://circleci.com/docs/2.0/caching/)
* [Clear project dependency cache](https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache)
> Remove core-stable CircleCI job

- faunadb-common/src/main/java/com/faunadb/common/http/HttpClient.java
- project/Settings.scala
There were some errors triggered during Java/ScalaDoc generation. In order to test, run:
```sh
sbt packageDoc
```
These fixes are required for Pronghorn.
> Fix JavaDoc issues

- README.md
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-common/src/main/java/com/faunadb/common/http/ResponseBodyStringProcessor.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- faunadb-scala/src/main/scala/faunadb/streaming/BodyValueFlowProcessor.scala
- faunadb-scala/src/main/scala/faunadb/streaming/SnapshotEventFlowProcessor.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- project/Dependencies.scala
This PR is built on top of the Jdk11 client migration proposal https://github.com/fauna/faunadb-jvm/pull/270
This PR proposes a Streaming API based on the `java.concurrent.Flow` which offers a strong interoperability via the reactive-streams initiative.
```scala
/**
* Creates a subscription to the result of the given read-only expression. When
* executed, the expression must only perform reads and produce a single
* streamable type, such as a reference or a version. Expressions that attempt
* to perform writes or produce non-streamable types will result in an error.
* Otherwise, any expression can be used to initiate a stream, including
* user-defined function calls.
*
* @param expr the query to subscribe to.
* @param fields fields to opt-in on the events.
* @param snapshot if true the …
```
> DRV-301: Streaming API for scala driver

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/errors/BadRequestException.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientFixture.scala
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
The goal of this PR is to:
- test the current limitation regarding the max number of streams per connection
- offer a nicer exception to the user to handle this error case
Given a situation where 100 streams are already running on a connection and an additional call to `client.stream` is made, it will result in:
- a `BadRequestException("the maximum number of streams has been reached for this client")` exception returned to the caller of `client.stream`
- each 100 open streams will fail by receiving on their subscriber `onError` handler the exception `java.io.IOException: GOAWAY received`
The user experience is not great for the subscriber in that case but I am not sure catching all `IOException` for inspection is a better idea.
To get there I had to perform a couple of changes:
- each …
> DRV-319: introduce cleaner error for max_concurrent_streams

- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Restoring test cases evaluating `Contains` function since now the CI pipeline should be supporting them.
> Restore test cases evaluating Contains function

- CHANGELOG.txt
- README.md
- project/Settings.scala
* Upgrade to Java 11
* Upgrade project dependencies
* Replace Netty HTTP Client with Java HTTP client
* Change from Basic to Bearer authentication scheme
* Add streaming API to the FaunaClient
* Add Third-party Auth functions: CurrentIdentity(), HasCurrentIdentity(), CurrentToken(),
HasCurrentToken(), CreateAccessProvider(), AccessProvider(), AccessProviders()
> Release 4.0.0

- CHANGELOG.txt
- faunadb-scala/src/main/scala/faunadb/values/Field.scala
- faunadb-scala/src/test/scala/faunadb/FieldSpec.scala
the main goal here is to adds the ability to combine 2 pre-existent `Field`. Currently we have the ability
to:
```scala
val DataField = Field("data")
val ZField = DataField("x", "y", "z")
```
but we cannot do combine pre-existents fields, so now can can do:
```scala
val DataField = Field("data")
val XField = Field("x")
val YField = Field("y")
val ZField = DataField.at(XField).at(YField)
```
I also created a `FieldSpec` to tests some of the field extractions
> Adds ability to combine fields + some tests

- faunadb-scala/src/main/scala/faunadb/query/package.scala
This PR makes sure we are not recreating the same value over and over again.
I kept `Null()` as a `def` to not break binary compatibility.
> do not reallocate Expr(NullV)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
This PR makes sure we are always sending the `X_QUERY_TIMEOUT` header.
I did a bit of cleanup to reduce allocations of `Duration` objects on the way.
> DRV-522: always send query timeout header

- README.md
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/types/MetricsResponse.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/MetricsResponseSpec.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/values/Metrics.scala
- faunadb-scala/src/main/scala/faunadb/values/MetricsResponse.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/MetricsResponseSpec.scala
Responses from Fauna include all sorts of extra headers:
'x-byte-read-ops': '34',
'x-byte-write-ops': '0',
'x-compute-ops': '2',
'x-faunadb-build': '20.11.00.rc8-01f9c94',
'x-query-bytes-in': '120',
'x-query-bytes-out': '4459',
'x-query-time': '7',
'x-read-ops': '27',
'x-storage-bytes-read': '3047',
'x-storage-bytes-write': '0',
'x-txn-retries': '0',
'x-txn-time': '1605653866258457',
'x-write-ops': '0'
This PR introduces an additional 'queryWithMetrics' method that can provide all those metrics values alongside with query response.
https://faunadb.atlassian.net/browse/DRV-551
> DRV-551: Expose billing metrics #299c

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
This PR is a quick fix for an incomplete implementation of https://github.com/fauna/faunadb-jvm/pull/295
The missing parts are:
- in the Java client, the `Builder` does not enable the user to set `userAgent`.
- in the Scala client, the `Builder` does not propagate the `userAgent` to the `Connection`.
> fix broken user-agent propagation

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
The driver throws the following error from time to time.
```
java.util.concurrent.CompletionException: java.io.IOException: HTTP/1.1 header parser received no bytes
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
at java.net.http/jdk.internal.net.http.Http1Response.onReadError(Unknown Source)
at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Unknown Source)
at …
```
> OSS-770: handle 'HTTP/1.1 header parser received no bytes'

- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
The error response can contain a `ref` field in case of 409 which points to document that was contended on.
However the parsing of `QueryError` is strict and fails on unknown fields.
```
faunadb.errors.UnknownException: Unparseable service com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ref" (class faunadb.QueryError), not marked as ignorable (5 known properties: "position", "description", "code", "failures", "cause"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: faunadb.QueryError["ref"]) response.
at faunadb.FaunaClient$$anonfun$parseErrors$1$1.applyOrElse(FaunaClient.scala:383)
at faunadb.FaunaClient$$anonfun$parseErrors$1$1.applyOrElse(FaunaClient.scala:380)
at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417) …
```
> OSS-768: do not fail to deserialize unknown field - not strict

- .circleci/config.yml
- project/Dependencies.scala
- project/Settings.scala
- project/plugins.sbt
https://github.com/scala/scala/releases/tag/v2.12.13
> scala 2.12.13

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/streaming/BodyValueFlowProcessor.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/streaming/BodyValueFlowProcessor.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
This reverts commit e7d38cf84afa84b05b9593d7882d0e41f4c25b0c.
@erickpintor determined that this reverted code is causing the following issue: https://faunadb.atlassian.net/browse/FE-1880
Reverting the commit to unblock set streaming release for the JVM driver.
> Revert "OSS-895 [java] Driver needs to detect and throw an error upon loss of networking (#323)"
