fauna/faunadb-jvm

- build.sbt
- faunadb-java/src/main/java/com/faunadb/client/HttpResponses.java
- faunadb-java/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java/src/main/java/com/faunadb/client/types/Set.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java/src/test/java/com/faunadb/client/ObjectCodecSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-java/src/test/resources/logback.xml
- faunadb-scala/src/main/scala/faunadb/HttpResponses.scala
- faunadb-scala/src/test/resources/logback.xml
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
> New error format

- faunadb-scala/src/main/scala/faunadb/query/Language.scala
- faunadb-scala/src/main/scala/faunadb/types/Var.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
Bulk of initial query language API unification.
> Revised dsl

- faunadb-scala/src/main/scala/faunadb/query/QueryMacros.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
> emit underscores for unused lambda vars

- faunadb-java/src/main/java/com/faunadb/client/response/Index.java
Creates a custom deserializer for index terms so we keep the api consistent between index terms as both paths and fields constructors.
> Attempts to keep compatibility with both field and path terms

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Lets wait until travis finish before merging this commit.
> Fix travis timout

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Fixes travis build since `await` helper waits for 5 seconds before timing out
> Using await function on all futures so we can control timeouts

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
> Making varargs functions compose with other expressions

- build.sbt
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/types/Codec.java
- Updates outdated libraries docs
- Fix docs build
- Disable doclint for java
> Fix doc build

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
I've tried to use a lambda this time. I think that is preferable in Scala.
> Adding session client to scala driver

- build.sbt
> Fix javadoc links between modules

- README.md
- build.sbt
I'll tag at 826414d once this is merged.
> Release 0.3.0

- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
Closes https://github.com/faunadb/sales-engineering/issues/224
> Moving lambdas to the last argument on Scala driver

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
Closes https://github.com/faunadb/sales-engineering/issues/223
> Moving lambdas to the last argument

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
Closes: https://github.com/faunadb/faunadb-jvm/issues/65
> Language class javadoc should refer to Expr instead of Value

- faunadb-java/src/test/java/com/faunadb/client/test/FaunaDBTest.java
Closes: https://github.com/faunadb/sales-engineering/issues/236
> Dropping database after tests run on java driver

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Closes: https://github.com/faunadb/sales-engineering/issues/239
> Dropping database after tests run for scala driver

- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Fixes failing tests on latest versions of FaunaDB.
> Fix specs for changes in insert response

- LICENSE
- README.md
- build.sbt
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/query/Pagination.java
- faunadb-java/src/main/java/com/faunadb/client/types/Value.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
Part of https://github.com/faunadb/sales-engineering/issues/348.
Does not make any code changes.
> Reterm client as driver; update links

- .travis.yml
- README.md
- build.sbt
- codecov.yml
- project/plugins.sbt
Code coverage integration with codecov.
> Setup code coverage

- faunadb-android/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-android/src/test/java/com/faunadb/client/AndroidClientSpec.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/errors/PermissionDeniedException.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/test/java/com/faunadb/client/JavaClientSpec.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
I realized that the server returns 403 status code but we weren't handling it appropriately, it was handled as `UnknowException`
> adds PermissionDeniedException class

- .travis.yml
- CHANGELOG.txt
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
close https://github.com/faunadb/sales-engineering/issues/453
> change default cloud url

- CHANGELOG.txt
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
Closes: https://github.com/faunadb/sales-engineering/issues/357
> Adding optional ts parameter to get function

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Fixes: https://github.com/fauna/sales-engineering/issues/526
> Fix constraint violation test for scala driver

- CHANGELOG.txt
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
close https://github.com/fauna/sales-engineering/issues/515
> adds support for `at` function

- CHANGELOG.txt
- faunadb-android/src/test/java/com/faunadb/client/AndroidClientSpec.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-java/src/test/java/com/faunadb/client/JavaClientSpec.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
close https://github.com/fauna/sales-engineering/issues/497
> adds KeyFromSecret function

- CHANGELOG.txt
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Deserializer.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
- faunadb-scala/src/main/scala/faunadb/jackson/ValueDeserializer.scala
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Codec.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/DeserializationSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
close https://github.com/fauna/sales-engineering/issues/506
> adds support for `@bytes` type

- README.md
> Add basic example to readme file

- CHANGELOG.txt
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Deserializer.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
- faunadb-scala/src/main/scala/faunadb/jackson/ValueDeserializer.scala
- faunadb-scala/src/main/scala/faunadb/query/QueryMacros.scala
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
close https://github.com/fauna/sales-engineering/issues/499
> Adds support for @query type

- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Codec.scala
- faunadb-scala/src/main/scala/faunadb/values/CodecMacro.scala
- faunadb-scala/src/main/scala/faunadb/values/Field.scala
- faunadb-scala/src/main/scala/faunadb/values/Time.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/CodecSpec.scala
Currently this PR only includes scala code, I'll start implement the feature for java and open a separate PR.
> Automatically generate codecs for use defined classes

- build.sbt
- project/plugins.sbt
To support CI-based driver releases.
> Add sbt-pgp and sbt-sonatype to build

- CHANGELOG.txt
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
Fixes: https://github.com/fauna/faunadb-jvm/issues/112
Also fix typos reported at: https://github.com/fauna/faunadb-jvm/issues/110
> Fix possible NPEs when checking for failing queries

- CHANGELOG.txt
- README.md
- build.sbt
- faunadb-java-dsl/src/main/java/com/faunadb/client/errors/FaunaException.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Codecs.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Constructors.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Decoder.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Encoder.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Enums.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/FaunaConstructor.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/FaunaEnum.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/FaunaField.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/FaunaIgnore.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Field.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Properties.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Result.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Types.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/DecoderSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/EncoderSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/ObjectCodecSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
- project/plugins.sbt
closes https://github.com/fauna/sales-engineering/issues/226
> Adds java encoder/decoder for user types

- CHANGELOG.txt
- faunadb-android/src/test/java/com/faunadb/client/AndroidClientSpec.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
- faunadb-java/src/test/java/com/faunadb/client/JavaClientSpec.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
this pr includes
* `abort` function
* `casefold:` with `normalizer` parameter
* deprecate `next_id` function
* `new_id` function
* `singleton` function
* `events` function
* `identity` function
* `has_identity` function
> Adds missing functions

- CHANGELOG.txt
- build.sbt
> Revert "Release 2.1.0"

- CHANGELOG.txt
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- project/build.properties
> Fixes NullPointerException when inspecting UnknownException in Scala

- faunadb-android/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/errors/FaunaException.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Pagination.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
As an aside, javadocs should probably be part of the CI run.
> Fixup documentation after Java 8 upgrade.

- CHANGELOG.txt
- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/SerializationSpec.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
Posting this now; I'll finish tests for scala tomorrow.
> Expand Language to include more type-ful variants.

- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Field.java
I... think this is what you're asking for. Please advise.
> Field interface improvements.

- CHANGELOG.txt
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
Does this rise to the level of a CHANGELOG entry?
> Add FaunaClient.query(Expr...).

- faunadb-java-dsl/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/util/SymbolGenerator.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/dsl/DslSpec.java
Not commented, &c., but here's what Java lambda support might look like.
> Add support for Java lambda syntax in collection functions.

- build.sbt
- faunadb-android/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Constructors.java
- faunadb-java-dsl/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-java-dsl/src/test/java/com/faunadb/client/ObjectCodecSpec.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
> Remove Guava

- CHANGELOG.txt
- README.md
- build.sbt
Taking the opportunity to sync this driver's version with the database version it supports.
> Release 2.5.0

- CHANGELOG.txt
- README.md
- build.sbt
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
> Release 2.5.2

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-common/src/main/java/com/faunadb/common/http/HttpClient.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/errors/UnavailableException.java
- faunadb-java/src/main/java/com/faunadb/client/errors/UnknownException.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- Handle exceptions better
- Don't ignore FaunaExceptions
- minor: fix the release on error completion
> Error handling:

- build.sbt
- faunadb-scala/src/main/scala/faunadb/query/package.scala
[ENG-1376](https://faunadb.atlassian.net/browse/ENG-1376)
> ENG-1376: make Expr constructor private

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
This test can break in some executions
> Fix intermittent test

- README.md
- docs/java.md
- docs/scala.md
[DRV-118](https://faunadb.atlassian.net/browse/DRV-118)
> DRV-118: Remove extra indentations in code snippets examples

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
[DRV-133](https://faunadb.atlassian.net/browse/DRV-133)
> DRV-133: [java] Handle Null value response properly

- docs/java.md
- docs/scala.md
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-86](https://faunadb.atlassian.net/browse/DRV-86)
> DRV-86: [java] Add client-specified query timeout 

- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-134](https://faunadb.atlassian.net/browse/DRV-134)
> DRV-134: [scala] Handle Null value response properly

- CHANGELOG.txt
- README.md
- build.sbt
* Add client-specified query timeout
* Handle Null value responses properly
> Release 2.12.0

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-190](https://faunadb.atlassian.net/browse/DRV-190)
> DRV-190: [scala] Refactor Contains() into family of functions

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
[DRV-191](https://faunadb.atlassian.net/browse/DRV-191)
> DRV-191: [java] Refactor Contains() into family of functions

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-185](https://faunadb.atlassian.net/browse/DRV-185)
> DRV-185: [scala] Support for AccessProvider

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/types/Value.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
[DRV-186](https://faunadb.atlassian.net/browse/DRV-186)
> DRV-186: [java] Support for AccessProvider

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-150](https://faunadb.atlassian.net/browse/DRV-150)
> DRV-150: [scala] Fix test case covering nested database keys

- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
[DRV-144](https://faunadb.atlassian.net/browse/DRV-144)
> DRV-144: Compile and run tests for Scala 2.11.12

- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
[DRV-151](https://faunadb.atlassian.net/browse/DRV-151)
> DRV-151: [java] Fix test case covering nested database keys

- .circleci/config.yml
[DRV-218](https://faunadb.atlassian.net/browse/DRV-218)
> DRV-218 : Fix "Gather Results" step in CircleCI

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
[DRV-105](https://faunadb.atlassian.net/browse/DRV-105)
> DRV-105: [java] Add Reverse function

- .circleci/config.yml
- build.sbt
- faunadb-scala/src/main/scala/faunadb/values/CodecMacro.scala
- project/Dependencies.scala
- project/Settings.scala
[DRV-144](https://faunadb.atlassian.net/browse/DRV-144)
This PR depends on https://github.com/fauna/faunadb-jvm/pull/235.
> DRV-144: [scala] Compile and run tests for Scala 2.11.12

- CHANGELOG.txt
- README.md
- project/Settings.scala
Release 3.0.0
* Add Reverse() function
* Refactor Contains() into family of functions
* Add support for versioned query values
* Factor out Dependencies and Settings from sbt file
* Refactor blocking operations in ClientSpec with ScalaFutures
* Fix test case covering nested database keys
* Fix "Gather Results" step in CircleCI
* Fix test compile task for Scala 2.11 version
> Release 3.0.0

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
https://faunadb.atlassian.net/browse/DRV-304
> drv-304: Change Basic to Bearer for Driver authorization request header

- faunadb-scala/src/load/scala/faunadb/FaunaClientFixture.scala
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/CodecSpec.scala
- faunadb-scala/src/test/scala/faunadb/DeserializationSpec.scala
- faunadb-scala/src/test/scala/faunadb/SerializationSpec.scala
- project/Dependencies.scala
This PR updates all dependencies on the project so that the next release ships less dated libraries.
Only upgrading `scalatest` required a few mechanical code changes.
> Update all dependencies

- docs/scala.md
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/errors/FaunaException.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/types/Codec.java
- faunadb-java/src/main/java/com/faunadb/client/types/Deserializer.java
- faunadb-java/src/main/java/com/faunadb/client/types/Path.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/DeserializationSpec.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientFixture.scala
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- faunadb-scala/src/main/scala/faunadb/jackson/ValueDeserializer.scala
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Codec.scala
- faunadb-scala/src/main/scala/faunadb/values/Field.scala
- faunadb-scala/src/main/scala/faunadb/values/FieldPath.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- faunadb-scala/src/test/scala/faunadb/CodecSpec.scala
This PR contains basic cleanups recommended by scalac and Intellij.
> minor: warnings & code cleanup

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- project/Settings.scala
Bump to `4.0.0-SNAPSHOT` version.
> Bump up to 4.0.0-SNAPSHOT version

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
https://faunadb.atlassian.net/browse/DRV-276
> DRV-276: Alias Identity to CurrentIdentity (Scala)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
https://faunadb.atlassian.net/browse/DRV-277
> DRV-277: Alias HasIdentity to HasCurrentIdentity (Scala)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
https://faunadb.atlassian.net/browse/DRV-281
> DRV-281: Alias Identity to CurrentIdentity (Java)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
https://faunadb.atlassian.net/browse/DRV-282
> DRV-282: Alias HasIdentity to HasCurrentIdentity (Java)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
https://faunadb.atlassian.net/browse/DRV-278
> DRV-278: Add CurrentToken function (Scala)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
https://faunadb.atlassian.net/browse/DRV-279
> DRV-279: Add HasCurrentToken function (Scala)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
https://faunadb.atlassian.net/browse/DRV-284
> DRV-284: Add HasCurrentToken function (Java)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
https://faunadb.atlassian.net/browse/DRV-283
> DRV-283: Add CurrentToken Function (Java)

- .circleci/config.yml
- README.md
- project/Settings.scala
[DRV-314](https://faunadb.atlassian.net/browse/DRV-314)
> DRV-314: Upgrade to Java 11

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
https://faunadb.atlassian.net/browse/DRV-280
> DRV-280: Add CreateAccessProvider (Scala)

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-java/src/test/java/com/faunadb/client/SerializationSpec.java
https://faunadb.atlassian.net/browse/DRV-285
> DRV-285: Add CreateAccessProvider function (Java)

- .circleci/config.yml
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
In order to test, run `sbt doc`.
> Fix sbt doc errors

- CHANGELOG.txt
- README.md
- project/Settings.scala
> Release 4.0.1

- LICENSE
A change in the license file.
This PR has been already approved:
https://github.com/fauna/faunadb-jvm/pull/288
> DRV-329: Updated license file

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
This PR enables users to pass a custom user-agent value to be sent on each request.
> DRV-503: enable user to pass a custom User-Agent

- project/Dependencies.scala
https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x#L32
https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION-2.x#L36
> jackson 2.12.1

- CHANGELOG.txt
- README.md
- project/Settings.scala
bumped to 4.1.0 release version
> bump to 4.1.0

- faunadb-java/src/main/java/com/faunadb/client/query/Language.java
- faunadb-java/src/main/java/com/faunadb/client/query/Pagination.java
- faunadb-java/src/main/java/com/faunadb/client/types/Value.java
- faunadb-scala/src/main/scala/faunadb/query/package.scala
- faunadb-scala/src/main/scala/faunadb/values/Value.scala
- Replace old `app.fauna.com` links with current doc links.
- Add doc links to functions that did not have them.
- Ensure that all doc links have the appropriate `lang=` query param.
- Fixed a few typos here and there.
> Update documentation links for the Java and Scala drivers:

- .gitignore
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Tests for Java and Scala fail that are checking function `ContainsValue` when it is used with index matching.
https://faunadb.atlassian.net/browse/OSS-797
> fix(OSS-797): Test fails sporadically

- CHANGELOG.txt
- README.md
- project/Settings.scala
> release: Bumped to 4.1.2

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-java/src/main/java/com/faunadb/client/errors/TransactionContentionException.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
This is a revival of https://github.com/fauna/faunadb-jvm/pull/315
https://faunadb.atlassian.net/browse/OSS-786
> OSS-786: dedicated error for 409

- CHANGELOG.txt
- README.md
- project/Settings.scala
Bumped to the new 4.2.0 version
> release: bumped to 4.2.0

- concourse/scripts/publish.sh
Added sbt options that haven't been moved from the Jenkins JVM release pipeline.
> fix(OSS-862): Added sbt_opts settings

- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/main/scala/faunadb/errors/CoreExceptionCodes.scala
- faunadb-scala/src/main/scala/faunadb/errors/FaunaException.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
- project/Dependencies.scala
**Overview**
This PR introduces new exceptions hierarchy feature:
https://docs.google.com/document/d/1VKRmSfm6gqWjVwImORz8DiGRvitRTbvIckIwcnS57TA/edit#heading=h.u3vzh3jcb8mu
[Jira ticket](https://faunadb.atlassian.net/browse/OSS-864)
> OSS-880: implement new driver exceptions hierarchy

- faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
See [OSS-977](https://faunadb.atlassian.net/browse/OSS-977)
> OSS-977: added message to Unauthorize exception

- faunadb-common/src/main/java/com/faunadb/common/Connection.java
See [OSS-961](https://faunadb.atlassian.net/browse/OSS-961)
> OSS-961: added 'Keep-Alive' header

- .circleci/config.yml
- faunadb-java/src/main/java/com/faunadb/client/streaming/EventFields.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
Changes:
* New event field;
* Test cases.
> ENG-3044: Introduce set streaming to the java driver

- .circleci/config.yml
- faunadb-common/src/main/java/com/faunadb/common/Connection.java
- faunadb-java/src/main/java/com/faunadb/client/streaming/EventFields.java
- faunadb-java/src/test/java/com/faunadb/client/ClientSpec.java
- faunadb-scala/src/load/scala/faunadb/FaunaClientLoadSpec.scala
- faunadb-scala/src/main/scala/faunadb/FaunaClient.scala
- faunadb-scala/src/test/scala/faunadb/ClientSpec.scala
Merge main into v4.
- debug auth0 (#330)
- OSS-895 [java] Driver needs to detect and throw an error upon loss of networking (#323)
- Revert "OSS-895 [java] Driver needs to detect and throw an error upon loss of networking (#323)" (#351)
- ENG-3044: Introduce set streaming to the java driver (#346)
- ENG-3044: Introduce set streaming to the Scala driver (#347)
> v4 mergeInMain - release set streaming

- CHANGELOG.txt
- README.md
- project/Settings.scala
> Release notes for 4.3.0 (set-streaming)
